// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRecentProject(arg1:string):Promise<Array<string>>;

export function GetRecentProjects():Promise<Array<string>>;

export function LoadProcfile(arg1:string):Promise<void>;

export function OpenFileDialog():Promise<string>;

export function RestartProcess(arg1:string):Promise<void>;

export function SaveLog(arg1:string,arg2:string):Promise<string>;

export function SetGlobalAutoRestart(arg1:boolean):Promise<void>;

export function StartAllProcesses():Promise<void>;

export function StartProcess(arg1:string):Promise<void>;

export function StopAllProcesses():Promise<void>;

export function StopProcess(arg1:string):Promise<void>;
