// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRecentProject(arg1) {
  return window['go']['main']['App']['AddRecentProject'](arg1);
}

export function GetRecentProjects() {
  return window['go']['main']['App']['GetRecentProjects']();
}

export function LoadProcfile(arg1) {
  return window['go']['main']['App']['LoadProcfile'](arg1);
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function RestartProcess(arg1) {
  return window['go']['main']['App']['RestartProcess'](arg1);
}

export function SaveLog(arg1, arg2) {
  return window['go']['main']['App']['SaveLog'](arg1, arg2);
}

export function SetGlobalAutoRestart(arg1) {
  return window['go']['main']['App']['SetGlobalAutoRestart'](arg1);
}

export function StartAllProcesses() {
  return window['go']['main']['App']['StartAllProcesses']();
}

export function StartProcess(arg1) {
  return window['go']['main']['App']['StartProcess'](arg1);
}

export function StopAllProcesses() {
  return window['go']['main']['App']['StopAllProcesses']();
}

export function StopProcess(arg1) {
  return window['go']['main']['App']['StopProcess'](arg1);
}
