// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddRecentProject(arg1:string):Promise<Array<string>>;

export function AskOpenCode(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CheckOpenCode():Promise<string>;

export function EnableProcess(arg1:string):Promise<void>;

export function GetActivePorts():Promise<Array<main.PortInfo>>;

export function GetAppIcon(arg1:string):Promise<string>;

export function GetDemoProcfilePath():Promise<string>;

export function GetInstalledApps():Promise<Array<string>>;

export function GetProcfileContent():Promise<string>;

export function GetRecentProjects():Promise<Array<string>>;

export function GetSettings():Promise<Record<string, string>>;

export function KillPort(arg1:number):Promise<void>;

export function LoadProcfile(arg1:string):Promise<void>;

export function OpenFileDialog():Promise<string>;

export function OpenFileInEditor(arg1:string,arg2:number):Promise<void>;

export function RestartProcess(arg1:string):Promise<void>;

export function SaveLog(arg1:string,arg2:string):Promise<string>;

export function SaveProcfileContent(arg1:string):Promise<void>;

export function SaveSetting(arg1:string,arg2:string):Promise<void>;

export function SetGlobalAutoRestart(arg1:boolean):Promise<void>;

export function StartAllProcesses():Promise<void>;

export function StartProcess(arg1:string):Promise<void>;

export function StopAllProcesses():Promise<void>;

export function StopProcess(arg1:string):Promise<void>;
