// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRecentProject(arg1) {
  return window['go']['main']['App']['AddRecentProject'](arg1);
}

export function AskOpenCode(arg1, arg2, arg3) {
  return window['go']['main']['App']['AskOpenCode'](arg1, arg2, arg3);
}

export function CheckOpenCode() {
  return window['go']['main']['App']['CheckOpenCode']();
}

export function EnableProcess(arg1) {
  return window['go']['main']['App']['EnableProcess'](arg1);
}

export function GetActivePorts() {
  return window['go']['main']['App']['GetActivePorts']();
}

export function GetAppIcon(arg1) {
  return window['go']['main']['App']['GetAppIcon'](arg1);
}

export function GetInstalledApps() {
  return window['go']['main']['App']['GetInstalledApps']();
}

export function GetRecentProjects() {
  return window['go']['main']['App']['GetRecentProjects']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function KillPort(arg1) {
  return window['go']['main']['App']['KillPort'](arg1);
}

export function LoadProcfile(arg1) {
  return window['go']['main']['App']['LoadProcfile'](arg1);
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function OpenFileInEditor(arg1, arg2) {
  return window['go']['main']['App']['OpenFileInEditor'](arg1, arg2);
}

export function RestartProcess(arg1) {
  return window['go']['main']['App']['RestartProcess'](arg1);
}

export function SaveLog(arg1, arg2) {
  return window['go']['main']['App']['SaveLog'](arg1, arg2);
}

export function SaveSetting(arg1, arg2) {
  return window['go']['main']['App']['SaveSetting'](arg1, arg2);
}

export function SetGlobalAutoRestart(arg1) {
  return window['go']['main']['App']['SetGlobalAutoRestart'](arg1);
}

export function StartAllProcesses() {
  return window['go']['main']['App']['StartAllProcesses']();
}

export function StartProcess(arg1) {
  return window['go']['main']['App']['StartProcess'](arg1);
}

export function StopAllProcesses() {
  return window['go']['main']['App']['StopAllProcesses']();
}

export function StopProcess(arg1) {
  return window['go']['main']['App']['StopProcess'](arg1);
}
